PUGX\Cmf\PageBundle\Document\Page:
    uri_schema: /{menu_path}
    token_providers:
        menu_path: [menu_path, {}]
    conflict_resolver: auto_increment
    defunct_route_handler: leave_redirect
