services:
  pugx_cmf_page.initializer:
    class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
    tags:
      - { name: doctrine_phpcr.initializer }
    arguments:
      - PUGXCmfPageBundle
      - [ /cms/content ]
  pugx_cmf_page.menu_initializer:
      class: PUGX\Cmf\PageBundle\Initializer\MenuInitializer
      tags:
        - { name: doctrine_phpcr.initializer }
      arguments:
        - @cmf_menu.provider
        - %pugx_cmf_page.menu%
  pugx_cmf_page.generic_controller:
    class: PUGX\Cmf\PageBundle\Controller\GenericController
    arguments:
      - @templating
      - PUGXCmfPageBundle:Document:default.html.twig
      - @fos_rest.view_handler
  pugx_cmf_page.menu_tree_block:
    class: PUGX\Cmf\PageBundle\Block\MenuBlockService
    tags:
      - { name: sonata.block }
    arguments:
      - pugx_cmf_page.menu_tree_block
      - @templating
      - @cmf_menu.provider
  pugx_cmf_page.page_admin:
    class: PUGX\Cmf\PageBundle\Admin\PageAdmin
    tags:
      - { name: sonata.admin, manager_type: doctrine_phpcr, group: dashboard.cmf, label_catalogue: PUGXCmfPageBundle, label: dashboard.label_page, label_translator_strategy: sonata.admin.label.strategy.underscore }
    arguments:
      - ~
      - PUGX\Cmf\PageBundle\Document\Page
      - SonataAdminBundle:CRUD
    calls:
      - [ setRouteBuilder, [@sonata.admin.route.path_info_slashes] ]
      - [ setRootPath, [/cms/content] ]

#    pugx_cmf_page.example:
#        class: PUGX\Cmf\PageBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
