parameters:
  cmf_seo.admin_extension.class: PUGX\Cmf\PageBundle\Admin\Extension\SeoContentAdminExtension
  cmf_seo.form.type.seo_metadata.class: PUGX\Cmf\PageBundle\Form\Type\SeoMetadataType
services:
  pugx_cmf_page.initializer:
    class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
    tags:
      - { name: doctrine_phpcr.initializer }
    arguments:
      - PUGXCmfPageBundle
      - [ /cms/content ]
  pugx_cmf_page.menu_initializer:
      class: PUGX\Cmf\PageBundle\Initializer\MenuInitializer
      tags:
        - { name: doctrine_phpcr.initializer }
      arguments:
        - @cmf_menu.provider
        - %pugx_cmf_page.menu%
  pugx_cmf_page.generic_controller:
    class: PUGX\Cmf\PageBundle\Controller\GenericController
    arguments:
      - @templating
      - PUGXCmfPageBundle:Document:default.html.twig
      - @fos_rest.view_handler
  pugx_cmf_page.menu_tree_block:
    class: PUGX\Cmf\PageBundle\Block\MenuBlockService
    tags:
      - { name: sonata.block }
    scope: prototype
    arguments:
      - pugx_cmf_page.menu_tree_block
      - @templating
      - @cmf_menu.provider
      - @cmf_menu.node_admin
  pugx_cmf_page.page_admin:
    class: PUGX\Cmf\PageBundle\Admin\PageAdmin
    tags:
      - { name: sonata.admin, manager_type: doctrine_phpcr, group: dashboard.cmf, label_catalogue: PUGXCmfPageBundle, label: dashboard.label_page, label_translator_strategy: sonata.admin.label.strategy.underscore }
    arguments:
      - ~
      - PUGX\Cmf\PageBundle\Document\Page
      - SonataAdminBundle:CRUD
    calls:
      - [ setRouteBuilder, [@sonata.admin.route.path_info_slashes] ]
      - [ setRootPath, [/cms/content] ]

  pugx_cmf_page.routing_auto.menu_path_provider:
    class: PUGX\Cmf\PageBundle\RoutingAuto\TokenProvider\MenuPathTokenProvider
    arguments: [ @cmf_routing_auto.slugifier ]
    tags:
      - { name: cmf_routing_auto.token_provider, alias: "menu_path" }

  # Overridden to use PUGXCmfPageBundle:Tree:tree.html.twig template
  sonata.admin.doctrine_phpcr.tree_controller:
    class: Sonata\DoctrinePHPCRAdminBundle\Controller\TreeController
    arguments:
      - @sonata.admin.doctrine_phpcr.phpcr_odm_tree
      - PUGXCmfPageBundle:Tree:tree.html.twig
      - %sonata_admin_doctrine_phpcr.tree_block.defaults%
      - %sonata_admin_doctrine_phpcr.tree_confirm_move%
    calls:
      - [ setContainer, [@service_container] ]

#    pugx_cmf_page.example:
#        class: PUGX\Cmf\PageBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
