# Framework Configuration
framework:
    translator:      { fallback: "%locale%" }

# Doctrine Configuration (needed for Jackalope Doctrine DBAL)
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        path:     "%database_path%"

# Doctrine PHPCR-ODM configuration
doctrine_phpcr:
    session:
        backend: "%phpcr_backend%"
        workspace: "%phpcr_workspace%"
        username: "%phpcr_user%"
        password: "%phpcr_password%"
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: "%kernel.debug%"

# Jackalope Metadata and Node Cache services
doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

# Cmf Configuration - TODO dovrebbe essere in WebgriffeCmfPageBundle ma se lo sposto in prepend config non lo prende...
cmf_core:
    persistence:
        phpcr:
          enabled: true
          use_sonata_admin: false
        # if you want another basepath
        # basepath: /custom/basepath
    publish_workflow: false

# Menu Configuration
knp_menu:
    twig: true

# Sonata Block Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

# Cmf Create Configuration
fos_rest:
    view:
        formats:
            json: true

# Cmf Routing Configuration
cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        persistence:
            phpcr:
                route_basepath: /cms/routes
        generic_controller: "webgriffe_cmf_page.generic_controller:indexAction"

# Cmf Auto Routing Configuration
cmf_routing_auto:
    persistence:
        phpcr:
            enabled: true

cmf_menu:
    persistence:
        phpcr:
            enabled: true
            use_sonata_admin: true

# Sonata Doctrine PHPCR Admin Configuration
sonata_doctrine_phpcr_admin:
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\Menu:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode
        Webgriffe\Cmf\PageBundle\Document\Page:
            valid_children:
                - all
