parameters:
    cmf_menu.persistence.phpcr.node_admin.class: Webgriffe\Cmf\PageBundle\Admin\MenuNodeAdmin

services:
  webgriffe_cmf_page.initializer:
    class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
    tags:
      - { name: doctrine_phpcr.initializer }
    arguments:
      - WebgriffeCmfPageBundle
      - [ /cms/content ]
  webgriffe_cmf_page.menu_initializer:
      class: Webgriffe\Cmf\PageBundle\Initializer\MenuInitializer
      tags:
        - { name: doctrine_phpcr.initializer }
      arguments:
        - /cms/menu # TODO: usare stesso parametro passato a cmf_menu come base path
        - { main: "Main Menu", footer: "Footer Menu" } # TODO: rendere questo array come parametro esterno
  webgriffe_cmf_page.generic_controller:
    class: Webgriffe\Cmf\PageBundle\Controller\GenericController
    arguments:
      - @templating
      - WebgriffeCmfPageBundle:Document:default.html.twig
      - @fos_rest.view_handler
  webgriffe_cmf_page.content_routes_loader_listener:
    class: Webgriffe\Cmf\PageBundle\EventListener\ContentRoutesLoader
    tags:
      - { name: doctrine_phpcr.event_listener, event: postLoad }
  webgriffe_cmf_page.page_admin:
    class: Webgriffe\Cmf\PageBundle\Admin\PageAdmin
    tags:
      - { name: sonata.admin, manager_type: doctrine_phpcr, group: dashboard.cmf, label_catalogue: WebgriffeCmfPageBundle, label: dashboard.label_page, label_translator_strategy: sonata.admin.label.strategy.underscore }
    arguments:
      - ~
      - Webgriffe\Cmf\PageBundle\Document\Page
      - SonataAdminBundle:CRUD
    calls:
      - [ setRouteBuilder, [@sonata.admin.route.path_info_slashes] ]
      - [ setRootPath, [/cms/content] ]

#    webgriffe_cmf_page.example:
#        class: Webgriffe\Cmf\PageBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
